### ISSUE TITLE
Hot Module Replacement isn't working

### ISSUE THREAD

**Issue by tiagosimoesdev** [adenvt/laravel-coreui-vue#22] opened 2019-02-23 22:16 UTC
**Describe the bug**
Running a clean installation after `npm run dev` and running `npm run hot` , after changing a vue file hmr doesn't do anything. 

**To Reproduce**
1- Clean install
2- npm run dev
3 - npm run hot
4 - Try changing a vue file , it doesn't do anything.

**Expected behavior**
HMR should work , after changing a vue file it should replace directly in browser without refresh the changes.

**Screenshots**
NA

**Platform (please complete the following information):**
 - OS: Windows 10 home
 - Browser chrome
 - Version 72.0.3626.109
 - Node Version v10.9.0
 - PHP Version 7.2.6

**Additional context**

**Comment by adenvt** [comment] 2019-03-05 07:00
I can't reproduce this issue on Ubuntu 16.04, but i haven't try on Windows yet. But i think it because browser cache.

**Comment by adenvt** [comment] 2019-03-18 16:00
related issue: https://github.com/JeffreyWay/laravel-mix/issues/1993

**Comment by adenvt** [comment] 2019-07-07 17:27
I close this because related issue has been closed

**Closed by adenvt** 2019-07-07 17:27 UTC
